In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-pertambangan/datapertambangan UAS.csv


In [2]:
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv('../input/data-pertambangan/datapertambangan UAS.csv')
df.head()

DER  Operating Profit Margin  Return On Asset  Sales Growth  Category
0  0.65                    6.663          0.06000      0.575136       4.0
1  1.69                   42.550          0.18000      0.189673       2.0
2  8.94                   15.080         -0.03865     -0.328694       2.0
3  5.43                  -30.070         -1.19000      0.000000       4.0
4  1.42                  265.900          0.01000      0.107550       2.0

In [4]:
np.asarray(df)

array([[ 6.50000000e-01,  6.66300000e+00,  6.00000000e-02,
         5.75135649e-01,  4.00000000e+00],
       [ 1.69000000e+00,  4.25500000e+01,  1.80000000e-01,
         1.89672802e-01,  2.00000000e+00],
       [ 8.94000000e+00,  1.50800000e+01, -3.86500070e-02,
        -3.28694489e-01,  2.00000000e+00],
       [ 5.43000000e+00, -3.00700000e+01, -1.19000000e+00,
         0.00000000e+00,  4.00000000e+00],
       [ 1.42000000e+00,  2.65900000e+02,  1.00000000e-02,
         1.07549938e-01,  2.00000000e+00],
       [ 2.62500000e+01, -1.09000000e+02, -3.00000000e-01,
        -3.71776683e-01,  2.00000000e+00],
       [ 5.80000000e-01,  1.48500000e+00,  4.10000000e-01,
         1.08581626e+00,  2.00000000e+00],
       [ 1.22200000e+01,  1.02000000e+00,  2.00000000e-02,
         7.09000000e-01,  1.00000000e+00],
       [ 4.70000000e-01,  9.74000000e+00,  4.60000000e-01,
         1.04443654e+00,  2.00000000e+00],
       [ 1.11000000e+00,  2.46400000e+01, -1.20227300e-01,
        -1.20273787e-01

In [5]:
import statsmodels.api as sm

In [6]:
x = df.drop('Category', axis=1)
x.head()

DER  Operating Profit Margin  Return On Asset  Sales Growth
0  0.65                    6.663          0.06000      0.575136
1  1.69                   42.550          0.18000      0.189673
2  8.94                   15.080         -0.03865     -0.328694
3  5.43                  -30.070         -1.19000      0.000000
4  1.42                  265.900          0.01000      0.107550

In [7]:
y = df['Category']
y.head()

0    4.0
1    2.0
2    2.0
3    4.0
4    2.0
Name: Category, dtype: float64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [9]:
x_train_sm = sm.add_constant(x_train)
x_train_sm

const        DER  Operating Profit Margin  Return On Asset  Sales Growth
9     1.0   1.110000                24.640000        -0.120227     -0.120274
27    1.0   0.530000                 4.853000         0.200000      0.688955
30    1.0   0.308144                 0.086652         0.056560      0.404536
4     1.0   1.420000               265.900000         0.010000      0.107550
14    1.0   0.470000                18.660000         0.030000      0.785000
20    1.0   0.310000               131.790000         0.080000      0.829775
18    1.0   3.320000              -120.220000        -0.020000      0.477539
6     1.0   0.580000                 1.485000         0.410000      1.085816
28    1.0   1.200000               208.160000         0.060000      0.220287
25    1.0   0.150000               304.460000         0.180000     -0.073845
13    1.0   1.500000               257.320000         0.030000      0.249980
3     1.0   5.430000               -30.070000        -1.190000      0.000000
16    1.0   0.320000                -9.540000        -0.020000      0.000000
7     1.0  12.220000                 1.020000         0.020000      0.709000
24    1.0  20.540000               -17.390000        -0.080000     -0.110911
17    1.0   0.310000               744.890000         0.100000      1.130136
29    1.0   0.061522                 1.659396         0.006723      0.870433
23    1.0   0.280000                 3.290000         0.000000      0.000000
12    1.0   0.900000                37.560000         0.010000      0.053012
26    1.0   0.770000                -2.540000        -0.060000      0.000000
5     1.0  26.250000              -109.000000        -0.300000     -0.371777
11    1.0   0.650000                 1.946000        -0.020000      0.436286
2     1.0   8.940000                15.080000        -0.038650     -0.328694
21    1.0   0.520000               699.710000         0.290000      0.539907

In [10]:
#logit_mod = sm.Logit(y_train, x_train_sm
                     
mnlogit_mod = sm.MNLogit(y_train, x_train_sm)
mnlogit_fit = mnlogit_mod.fit()

Optimization terminated successfully.
         Current function value: 0.630855
         Iterations 9


In [11]:
print (mnlogit_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:               Category   No. Observations:                   24
Model:                        MNLogit   Df Residuals:                       14
Method:                           MLE   Df Model:                            8
Date:                Wed, 06 Jul 2022   Pseudo R-squ.:                  0.2639
Time:                        11:56:51   Log-Likelihood:                -15.141
converged:                       True   LL-Null:                       -20.569
Covariance Type:            nonrobust   LLR p-value:                    0.2100
             Category=2       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       2.1797      1.411      1.545      0.122      -0.586       4.945
DER                        -0.0036      0.117     -0.031      0.976      -0.234       0.226


In [12]:
model = LogisticRegression(multi_class='auto')
model.fit(x_train, y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [13]:
model.predict_proba(x_test)[0:5]

array([[0.1740258 , 0.6323921 , 0.1935821 ],
       [0.21614075, 0.67140937, 0.11244988],
       [0.19418452, 0.70874832, 0.09706715],
       [0.17982605, 0.19111085, 0.6290631 ],
       [0.1270219 , 0.69222258, 0.18075553]])

In [14]:
predictions = model.predict(x_test)
predictions

array([2., 2., 2., 4., 2., 2., 2.])

In [15]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         1
         2.0       0.67      1.00      0.80         4
         4.0       1.00      0.50      0.67         2

    accuracy                           0.71         7
   macro avg       0.56      0.50      0.49         7
weighted avg       0.67      0.71      0.65         7



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
